var arrText = ['电话','浏览器','记事本','照相','收音机','邮箱','计算器','城堡游戏','ChromeApp','日历','文件夹','温度计'];
var arrDate = [
		{
			"name":"phone",
			"description":"电话",
			"link":"http://www.10086.cn/",
			"img":"img/01.png"
		},
		{
			"name":"browser",
			"description":"浏览器",
			"link":"http://www.firefox.com.cn/",
			"img":"img/02.png"
		},
		{
			"name":"notepad",
			"description":"记事本",
			"link":"https://www.yinxiang.com/",
			"img":"img/03.png"
		},
		{
			"name":"photo",
			"description":"照相",
			"link":"http://www.fengniao.com/",
			"img":"img/04.png"
		},
		{
			"name":"radio",
			"description":"收音机",
			"link":"http://www.fm101.cn/",
			"img":"img/05.png"
		},
		{
			"name":"email",
			"description":"邮箱",
			"link":"http://email.163.com/",
			"img":"img/06.png"
		},
		{
			"name":"calculator",
			"description":"计算器",
			"link":"http://cal.supfree.net/",
			"img":"img/07.png"
		},
		{
			"name":"castle",
			"description":"城堡游戏",
			"link":"http://www.ali213.net/",
			"img":"img/08.png"
		},
		{
			"name":"ChromeApp",
			"description":"ChromeApp",
			"link":"http://siteapp.baidu.com/",
			"img":"img/09.png"
		},
		{
			"name":"calendar",
			"description":"日历",
			"link":"http://rili.baidu.com/",
			"img":"img/10.png"
		},
		{
			"name":"folder",
			"description":"文件夹",
			"link":"http://yun.baidu.com/",
			"img":"img/11.png"
		},
		{
			"name":"thermometer",
			"description":"温度计",
			"link":"http://www.weather.com.cn/",
			"img":"img/12.png"
		}
	];